-- =============================================================================
-- БАЗА ДАННЫХ ДЛЯ TG-БОТА: ОПТИМИЗАЦИЯ ПОД РЕАЛЬНОЕ ВРЕМЯ И БЫСТРЫЕ ЗАПРОСЫ
-- =============================================================================
-- Порядок: сначала справочники и независимые таблицы, затем с FK.
-- Индексы под запросы бота: user_id, referrer_id, worker_id+status, is_active.
-- =============================================================================

-- 1. ПОЛЬЗОВАТЕЛИ (USERS) — ядро для бота
-- Запросы бота: get by user_id, get by referrer_id, update by user_id, insert
create table public.users (
  user_id bigint not null,
  username text null,
  full_name text null,
  photo_url text null,
  referrer_id bigint null,
  balance numeric(18, 2) not null default 0,
  worker_min_deposit numeric(18, 2) not null default 10,
  luck text not null default 'default',
  withdraw_message_type text not null default 'default',
  preferred_currency text not null default 'RUB',
  is_kyc boolean not null default false,
  web_registered boolean not null default false,
  email text null,
  country_code text null default 'RU',
  notifications_enabled boolean not null default true,
  trading_blocked boolean not null default false,
  is_worker boolean not null default false,
  last_login timestamptz null,
  login_count integer null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_pkey primary key (user_id),
  constraint users_luck_check check (luck in ('win', 'lose', 'default'))
);

create index idx_users_referrer on public.users (referrer_id) where referrer_id is not null;
create index idx_users_username on public.users (username) where username is not null;

-- 2. НАСТРОЙКИ (SETTINGS) — одна запись на проект, частые чтения
create table public.settings (
  id bigint generated by default as identity primary key,
  support_username text not null default 'Support_Agent',
  bank_details text null default 'Реквизиты не указаны',
  min_deposit numeric(18, 2) not null default 100,
  min_withdraw numeric(18, 2) not null default 500,
  is_tech_work boolean not null default false,
  created_at timestamptz not null default now()
);

-- Гарантированная одна строка настроек (для быстрого limit 1)
insert into public.settings (support_username, min_deposit, min_withdraw)
select 'Support_Agent', 100, 500
where not exists (select 1 from public.settings limit 1);

-- Миграция: добавить min_withdraw, если колонки нет (для существующих БД)
alter table public.settings add column if not exists min_withdraw numeric(18, 2) not null default 500;

-- 3. РЕКВИЗИТЫ ПО СТРАНАМ — справочник, запросы: по is_active + order by country_name
create table public.country_bank_details (
  id bigint generated by default as identity primary key,
  country_name text not null unique,
  country_code text not null,
  currency text not null,
  bank_details text not null,
  exchange_rate numeric(18, 6) not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_country_active_name on public.country_bank_details (is_active, country_name)
  where is_active = true;

-- Реквизиты только по РФ: одна запись «Россия» по умолчанию
insert into public.country_bank_details (country_name, country_code, currency, bank_details, exchange_rate, is_active)
values ('Россия', 'RU', 'RUB', 'Реквизиты не указаны. Укажите в боте: Админ → Реквизиты РФ.', 1, true)
on conflict (country_name) do nothing;

-- 4. ШАБЛОНЫ СООБЩЕНИЙ ВЫВОДА — справочник, запрос: is_active order sort_order
create table public.withdraw_message_templates (
  id bigint generated by default as identity primary key,
  message_type text not null unique,
  title text not null,
  description text not null,
  icon text null default '⚠️',
  button_text text null,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index idx_withdraw_active_sort on public.withdraw_message_templates (is_active, sort_order)
  where is_active = true;

-- 5. ЗАЯВКИ НА ДЕПОЗИТ — частые запросы: по worker_id + status = pending, по id
create table public.deposit_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (user_id) on delete cascade,
  worker_id bigint null references public.users (user_id) on delete set null,
  amount_local numeric(18, 2) not null,
  amount_usd numeric(18, 2) not null,
  currency text not null,
  method text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  processed_at timestamptz null,
  constraint deposit_requests_status_check check (status in ('pending', 'approved', 'rejected'))
);

-- Критично для бота: быстрый список pending по воркеру
create index idx_deposits_worker_pending on public.deposit_requests (worker_id, created_at desc)
  where status = 'pending';
create index idx_deposits_user on public.deposit_requests (user_id, created_at desc);

-- 6. СДЕЛКИ (TRADES) — веб-приложение
create table public.trades (
  id text not null default gen_random_uuid()::text primary key,
  user_id bigint not null references public.users (user_id) on delete cascade,
  pair text not null,
  symbol text not null,
  type text not null check (type in ('Long', 'Short')),
  amount numeric(18, 2) not null,
  leverage int null default 1,
  entry_price numeric(18, 8) not null,
  final_price numeric(18, 8) null,
  start_time bigint not null,
  duration_seconds int not null,
  status text not null default 'active' check (status in ('active', 'completed', 'cancelled')),
  final_pnl numeric(18, 2) null,
  is_winning boolean null,
  forced_result text null check (forced_result is null or forced_result in ('win', 'lose')),
  created_at timestamptz not null default now()
);

create index idx_trades_user_status on public.trades (user_id, status);
create index idx_trades_created on public.trades (created_at desc);

-- 7. ЛОГ ИЗМЕНЕНИЙ МАМОНТОВ — аудит
create table public.mammoth_change_log (
  id bigserial primary key,
  worker_id bigint not null references public.users (user_id) on delete cascade,
  mammoth_id bigint not null references public.users (user_id) on delete cascade,
  change_type text not null,
  old_value text null,
  new_value text null,
  created_at timestamptz not null default now()
);

create index idx_changelog_mammoth_created on public.mammoth_change_log (mammoth_id, created_at desc);

-- 8. ЗАМЕТКИ ПО МАМОНТАМ
create table public.mammoth_notes (
  id bigserial primary key,
  worker_id bigint not null references public.users (user_id) on delete cascade,
  mammoth_id bigint not null references public.users (user_id) on delete cascade,
  note_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_notes_mammoth on public.mammoth_notes (mammoth_id);

-- 9. ШАБЛОНЫ СООБЩЕНИЙ ВОРКЕРА
create table public.message_templates (
  id bigserial primary key,
  worker_id bigint not null references public.users (user_id) on delete cascade,
  template_name text not null,
  template_text text not null,
  template_type text not null,
  trigger_event text null,
  is_active boolean not null default true,
  usage_count int not null default 0,
  created_at timestamptz not null default now()
);

create index idx_templates_worker_type on public.message_templates (worker_id, template_type);

-- 10. ПРАВИЛА АВТОМАТИЗАЦИИ
create table public.automation_rules (
  id bigserial primary key,
  worker_id bigint not null references public.users (user_id) on delete cascade,
  mammoth_id bigint not null references public.users (user_id) on delete cascade,
  rule_type text not null,
  rule_config jsonb not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (worker_id, mammoth_id, rule_type)
);

create index idx_automation_mammoth on public.automation_rules (mammoth_id);

-- 11. НАСТРОЙКИ УВЕДОМЛЕНИЙ ВОРКЕРА
create table public.worker_notification_settings (
  worker_id bigint not null primary key references public.users (user_id) on delete cascade,
  notify_new_registration boolean not null default true,
  notify_deposit boolean not null default true,
  notify_deposit_min_amount numeric(18, 2) null default 100,
  notify_withdrawal_request boolean not null default true,
  notify_trade boolean not null default false,
  notify_mammoth_login boolean not null default false,
  notification_channel text null default 'telegram',
  webhook_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =============================================================================
-- ТРИГГЕРЫ: updated_at и лог изменений
-- =============================================================================

-- Универсальная функция: обновить updated_at
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- users: updated_at + лог изменений баланса/реферера
create or replace function log_mammoth_changes()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  if old.referrer_id is distinct from new.referrer_id then
    insert into mammoth_change_log (worker_id, mammoth_id, change_type, old_value, new_value)
    values (
      coalesce(new.referrer_id, old.referrer_id),
      new.user_id,
      'referrer',
      old.referrer_id::text,
      new.referrer_id::text
    );
  end if;
  if old.balance is distinct from new.balance and new.referrer_id is not null then
    insert into mammoth_change_log (worker_id, mammoth_id, change_type, old_value, new_value)
    values (new.referrer_id, new.user_id, 'balance', old.balance::text, new.balance::text);
  end if;
  return new;
end;
$$;

create trigger trigger_users_updated
  before update on public.users for each row execute function log_mammoth_changes();

-- country_bank_details: updated_at при обновлении
create trigger trigger_country_updated
  before update on public.country_bank_details for each row execute function set_updated_at();

-- worker_notification_settings: updated_at при обновлении
create trigger trigger_worker_notif_updated
  before update on public.worker_notification_settings for each row execute function set_updated_at();

-- automation_rules: updated_at при обновлении
create trigger trigger_automation_updated
  before update on public.automation_rules for each row execute function set_updated_at();

-- mammoth_notes: updated_at при обновлении
create trigger trigger_notes_updated
  before update on public.mammoth_notes for each row execute function set_updated_at();

-- =============================================================================
-- REALTIME (Supabase): раскомментировать при необходимости подписки с веб-приложения
-- =============================================================================
-- alter publication supabase_realtime add table public.users;
-- alter publication supabase_realtime add table public.deposit_requests;
-- alter publication supabase_realtime add table public.trades;

-- =============================================================================
-- ДЛЯ УЖЕ СУЩЕСТВУЮЩЕЙ БАЗЫ: только новые индексы и триггеры (таблицы не пересоздавать)
-- =============================================================================
alter table public.users add column if not exists trading_blocked boolean not null default false;
alter table public.users add column if not exists is_worker boolean not null default false;
-- create index if not exists idx_deposits_worker_pending on public.deposit_requests (worker_id, created_at desc) where status = 'pending';
-- create index if not exists idx_country_active_name on public.country_bank_details (is_active, country_name) where is_active = true;
-- create index if not exists idx_withdraw_active_sort on public.withdraw_message_templates (is_active, sort_order) where is_active = true;
-- + добавить триггеры set_updated_at / log_mammoth_changes если их ещё нет
