-- =============================================================================
-- МИГРАЦИЯ: Криптокошельки для пополнения (отдельная таблица)
-- Сети: trc20 (USDT), ton, btc, sol. Один активный кошелёк на сеть или несколько.
-- =============================================================================

create table if not exists public.crypto_wallets (
  id bigint generated by default as identity primary key,
  network text not null,
  wallet_address text not null,
  label text null,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crypto_wallets_network_check check (network in ('trc20', 'ton', 'btc', 'sol'))
);

create index idx_crypto_wallets_active_network on public.crypto_wallets (is_active, network)
  where is_active = true;

comment on table public.crypto_wallets is 'Криптокошельки для приёма пополнений (USDT TRC20, TON, BTC, SOL)';
comment on column public.crypto_wallets.network is 'Сеть: trc20, ton, btc, sol';
comment on column public.crypto_wallets.wallet_address is 'Адрес кошелька для пополнения';
comment on column public.crypto_wallets.label is 'Подпись (например: USDT TRC20)';

-- Примеры: раскомментируйте и замените на свои адреса
-- insert into public.crypto_wallets (network, wallet_address, label, sort_order)
-- values
--   ('trc20', 'TYourUsdtTrc20Address...', 'USDT TRC20', 1),
--   ('ton', 'UQYourTonAddress...', 'TON', 2),
--   ('btc', 'bc1qYourBtcAddress...', 'Bitcoin', 3),
--   ('sol', 'YourSolanaAddress...', 'Solana', 4);
